/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilialGuaporeRouteImport } from './routes/filial-guapore'
import { Route as FilialPortugalRouteImport } from './routes/filial-portugal'
import { Route as FilialVilaSeixasRouteImport } from './routes/filial-vila-seixas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilialGuaporeRoute = FilialGuaporeRouteImport.update({
  id: '/filial-guapore',
  path: '/filial-guapore',
  getParentRoute: () => rootRouteImport,
} as any)
const FilialPortugalRoute = FilialPortugalRouteImport.update({
  id: '/filial-portugal',
  path: '/filial-portugal',
  getParentRoute: () => rootRouteImport,
} as any)
const FilialVilaSeixasRoute = FilialVilaSeixasRouteImport.update({
  id: '/filial-vila-seixas',
  path: '/filial-vila-seixas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filial-guapore': typeof FilialGuaporeRoute
  '/filial-portugal': typeof FilialPortugalRoute
  '/filial-vila-seixas': typeof FilialVilaSeixasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filial-guapore': typeof FilialGuaporeRoute
  '/filial-portugal': typeof FilialPortugalRoute
  '/filial-vila-seixas': typeof FilialVilaSeixasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/filial-guapore': typeof FilialGuaporeRoute
  '/filial-portugal': typeof FilialPortugalRoute
  '/filial-vila-seixas': typeof FilialVilaSeixasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/filial-guapore' | '/filial-portugal' | '/filial-vila-seixas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/filial-guapore' | '/filial-portugal' | '/filial-vila-seixas'
  id:
    | '__root__'
    | '/'
    | '/filial-guapore'
    | '/filial-portugal'
    | '/filial-vila-seixas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilialGuaporeRoute: typeof FilialGuaporeRoute
  FilialPortugalRoute: typeof FilialPortugalRoute
  FilialVilaSeixasRoute: typeof FilialVilaSeixasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filial-guapore': {
      id: '/filial-guapore'
      path: '/filial-guapore'
      fullPath: '/filial-guapore'
      preLoaderRoute: typeof FilialGuaporeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filial-portugal': {
      id: '/filial-portugal'
      path: '/filial-portugal'
      fullPath: '/filial-portugal'
      preLoaderRoute: typeof FilialPortugalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filial-vila-seixas': {
      id: '/filial-vila-seixas'
      path: '/filial-vila-seixas'
      fullPath: '/filial-vila-seixas'
      preLoaderRoute: typeof FilialVilaSeixasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilialGuaporeRoute: FilialGuaporeRoute,
  FilialPortugalRoute: FilialPortugalRoute,
  FilialVilaSeixasRoute: FilialVilaSeixasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
